name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    strategy:
      matrix:
        path: ["cg_space", "clamav", "database", "domain", "redis", "s3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate ${{ matrix.path }}
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    strategy:
      matrix:
        path: ["cg_space", "clamav", "database", "domain", "redis", "s3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt ${{ matrix.path }}
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}
