name: Terraform Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        module: ["s3", "database", "redis"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform test ${{ matrix.module }}
        working-directory: ${{ matrix.module }}
        env:
          CF_USER: ${{ vars.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: terraform test
