name: Terraform Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        module: ["s3"]
    steps:
      - uses: actions/checkout@v4

      - name: terraform test ${{ matrix.module }}
        uses: dflook/terraform-test@v1
        with:
          path: ${{ matrix.module }}
          variables: |
            cf_user = "${{ secrets.CF_USER }}"
            cf_password = "${{ secrets.CF_PASSWORD }}"
